//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockAnalyseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stock_Status
    {
        public int id { get; set; }
        public string cn_name { get; set; }
        public string en_name { get; set; }
        public string stock_status1 { get; set; }
    }
}
