//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockAnalyseModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StockAnalyseEntities : DbContext
    {
        public StockAnalyseEntities()
            : base("name=StockAnalyseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Stock_List> Stock_List { get; set; }
        public virtual DbSet<Stock_Status> Stock_Status { get; set; }
        public virtual DbSet<Stock_Transaction_Records> Stock_Transaction_Records { get; set; }
    }
}
