//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockAnalyseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stock_List
    {
        public int id { get; set; }
        public string ts_code { get; set; }
        public string symbol { get; set; }
        public string name { get; set; }
        public string area { get; set; }
        public string industry { get; set; }
        public string fullname { get; set; }
        public string enname { get; set; }
        public string market { get; set; }
        public string exchange { get; set; }
        public string curr_type { get; set; }
        public string list_status { get; set; }
        public string list_date { get; set; }
        public string is_hs { get; set; }
        public string delist_date { get; set; }
        public string Stock_Status { get; set; }
    }
}
